### ISSUE TITLE
Remote I/O Error on initiailze (Raspberry pi 4)

### ISSUE THREAD

**Issue by krmbn0576** [adafruit/Adafruit_CircuitPython_MMA8451#13]
```python3
import time
import board
import busio
import adafruit_mma8451

i2c = busio.I2C(board.SCL, board.SDA)
sensor = adafruit_mma8451.MMA8451(i2c)
```

I ran the above code in Raspberrypi 4 (Raspbian) and got the following error.

```
Traceback (most recent call last):
  File "/home/pi/Documents/accel.py", line 7, in <module>
    sensor = adafruit_mma8451.MMA8451(i2c)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_mma8451.py", line 103, in __init__
    while self._read_u8(_MMA8451_REG_CTRL_REG2) & 0x40 > 0:
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_mma8451.py", line 133, in _read_u8
    self._read_into(address, self._BUFFER, count=1)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_mma8451.py", line 129, in _read_into
    i2c.write_then_readinto(bytes([address & 0xFF]), buf, in_end=count)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 156, in write_then_readinto
    in_end=in_end,
  File "/home/pi/.local/lib/python3.7/site-packages/busio.py", line 118, in writeto_then_readfrom
    stop=stop,
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 85, in writeto_then_readfrom
    address, buffer_out[out_start:out_end], in_end - in_start
  File "/home/pi/.local/lib/python3.7/site-packages/Adafruit_PureIO/smbus.py", line 273, in read_i2c_block_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
OSError: [Errno 121] Remote I/O error
```

When I ran the following code, no error occurred.

```python3

import time
import board
import busio
import adafruit_mma8451

i2c = busio.I2C(board.SCL, board.SDA)
time.sleep(1)
sensor = adafruit_mma8451.MMA8451(i2c)
```

`time.sleep(0.5)` is not enough, needs `time.sleep(1)`.

I'm guessing that you'll need to wait for Blinka to complete its initialization before initializing MMA8451.

**Comment by duckman98** [comment]
Did you ever find a fix to this? I'm having exactly the same problem - all the same hardware too.

**Comment by dgarciarivas** [comment]
I implemented the time.sleep(1) call into the test code [provided](https://github.com/adafruit/Adafruit_CircuitPython_MMA8451/blob/master/examples/mma8451_simpletest.py) and it works now. Thanks @krmbn0576 !

**Comment by ladyada** [comment]
i think we could add it as long as we have a comment explaining why, please submit a PR!

**Comment by dherrada** [comment]
@dgarciarivas Yeah, a PR with this fix would be amazing. I'm sure you're not the only one having this issue so it would probably be very helpful

**Comment by dgarciarivas** [comment]
Did some more investigating. Seems like people who are having this issue may have not fully read the documentation on I2C with Raspberry Pi. Luckily, I stumbled upon this on another Adafruit sensor page: 

"To use this sensor, you must enable i2c slowdown on the Raspberry Pi device tree overlay. [Check out this guide for instructions!](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-stretching)"

Followed the instructions on that link, and the time.sleep(1) call after defining i2c was not needed. 

Hope this helps anyone out there!

**Comment by krmbn0576** [comment]
Thanks for resolving this! So this is a documentation error that i2c slowdown is not explained in the usage of MMA8451. I'll leave this issue open until the documentation is corrected so that future users don't have to deal with it.

**Comment by ladyada** [comment]
Older versions of the Raspberry Pi firmware do not have I2C clock stretching support so they don't work well with the MMA. Please ensure your firmware is updated to the latest version before continuing and slow down the I2C as explained here https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-stretching

added to learning guide!
@dherrada maybe add to the readme here

**Comment by dherrada** [comment]
@ladyada On it!

**Comment by krmbn0576** [comment]
Thank you for the update! 👍 👍 👍
